# Change these first
owner: byFrench # Your GitHub organization or username, where this repository lives
repo: status-uptime # The name of this repository

sites:
  - name: RolePlay Website
    url: https://rp.french.eu.org
  - name: Custom API.json
    url: https://api.french.qc.lu
  - name: My PlaceHolder
    url: https://placeholder.french.eu.org/images/splits/02/10.jpg
  - Name: Unofficial VRChat Website
    url: https://hello.vrchat.eu.org

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.e-girl.eu.org
  # baseUrl: /your-repo-name 
  logoUrl: https://status.e-girl.eu.org/custom/img/egirl-icon.png
  themeUrl: https://status.e-girl.eu.org/custom/css/egirl.css
  name: StatUwUs
  introTitle: "Informations"
  introMessage: "**StatUwUs** was set up to provide a history of the status of sites managed by byFrench."
  navbar:
    - title: Status
      href: /
    - title: Instagram
      href: https://www.instagram.com/antighostping
    - title: GitHub
      href: https://github.com/$OWNER

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
