# Change these first 
owner: byFrench # Your GitHub organization or username, where this repository lives
repo: status-uptime # The name of this repository

sites:
  - name: RolePlay Website
    url: https://rp.french.eu.org/ping
    icon: https://status.e-girl.eu.org/custom/img/status_favicon/roleplay.ico
  - name: Custom API.json
    url: https://api.french.qc.lu/ping
    icon: https://status.e-girl.eu.org/custom/img/status_favicon/api.ico
  - name: My PlaceHolder
    url: https://placeholder.french.eu.org/ping
    icon: https://status.e-girl.eu.org/custom/img/status_favicon/placeholder.ico

i18n:
  footer: "<span id='date'></span> &copy; <a href='//status.e-girl.eu.org' target='_self' title='StatUwUs' rel='noopener'>StatUwUs</a> <br> Powered by Upptime."

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.e-girl.eu.org
  # baseUrl: /your-repo-name 
  favicon: https://status.e-girl.eu.org/custom/img/favicon.png
  logoUrl: https://status.e-girl.eu.org/custom/img/egirl-icon.png
  #themeUrl: https://status.e-girl.eu.org/custom/css/status.css
  name: StatUwUs
  introTitle: "Informations"
  introMessage: "**StatUwUs** was set up to provide a history of the status of sites managed by a so-called e-girl who is not."
  navbar:
    - title: Status
      href: /
    - title: Instagram
      href: https://www.instagram.com/antighostping
    - title: GitHub
      href: https://github.com/$OWNER
  scripts:
    - src: https://status.e-girl.eu.org/custom/js/date.js
    #- src: https://status.e-girl.eu.org/custom/js/footer.js
    #- src: https://status.e-girl.eu.org/custom/js/change_favicon.js
  links:
    - rel: stylesheet
      href: https://status.e-girl.eu.org/custom/css/status.css
  metaTags:
    - name: "robots"
      content: "noindex, nofollow"
    - name: "googlebot"
      content: "noindex, nofollow"
    - name: "description"
      content: "StatUwUs is a simple status page for services and website used/created by a so-called e-girl who is not."
    - name: "author"
      content: "So-called e-girl who is not."


# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
