# Change these first 
owner: byFrench # Your GitHub organization or username, where this repository lives
repo: status-uptime # The name of this repository

sites:
  - name: RolePlay Website
    url: https://rp.french.eu.org/ping
    icon: https://status.e-girl.eu.org/custom/img/status_favicon/roleplay.ico
  - name: Custom API.json
    url: https://api.french.qc.lu/ping
    icon: https://status.e-girl.eu.org/custom/img/status_favicon/api.ico
  - name: My PlaceHolder
    url: https://placeholder.french.eu.org/ping
    icon: https://status.e-girl.eu.org/custom/img/status_favicon/placeholder.ico

i18n:
  allSystemsOperational: "All systems are operational. UwU"
  activeIncidents: "Active Incidents. UwU"
  footer: "<span id='date'>202X</span> &copy; <a href='//status.e-girl.eu.org' title='StatUwUs' rel='noopener'>StatUwUs</a> <br> Powered by Upptime."

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.e-girl.eu.org
  # baseUrl: /your-repo-name 
  favicon: https://status.e-girl.eu.org/custom/img/favicon.png
  logoUrl: https://status.e-girl.eu.org/custom/img/icon.png
  #themeUrl: https://status.e-girl.eu.org/custom/css/status.css
  name: StatUwUs
  introTitle: "Informations"
  introMessage: "**StatUwUs** was set up to provide a history of the status of sites managed by a so-called e-girl who is not."
  navbar:
    - title: Status
      href: /
  scripts:
    - src: https://status.e-girl.eu.org/custom/js/date.js
    - src: https://status.e-girl.eu.org/custom/js/fa-all.min.js
    #- src: https://status.e-girl.eu.org/custom/js/footer.js
    #- src: https://status.e-girl.eu.org/custom/js/change_favicon.js
  links:
    - rel: stylesheet
      href: https://status.e-girl.eu.org/custom/css/status.css
    - rel: stylesheet
      href: https://status.e-girl.eu.org/custom/css/icon-bar.css
    - rel: stylesheet
      href: https://status.e-girl.eu.org/custom/css/fa-all.min.css
  customHeadHtml: "

  <meta property='og:type' content='website'>
  <meta property='og:locale' content='fr' />
  <meta property='og:site_name' content='So-called e-girl who is not.' />
  <meta property='og:title' content='StatUwUs'>
  <meta property='og:description' content='StatUwUs is a simple status page for services and website used/created by a so-called e-girl who is not.'>
  <meta property='og:image' content='https://status.e-girl.eu.org/custom/img/banner.jpg'>
  <meta property='twitter:card' content='summary_large_image'>
  <meta property='twitter:title' content='StatUwUs'>
  <meta property='twitter:description' content='StatUwUs is a simple status page for services and website used/created by a so-called e-girl who is not.'>
  <meta property='twitter:image' content='https://status.e-girl.eu.org/custom/img/banner.jpg'>

  "
  metaTags:
    - name: "robots"
      content: "noindex, nofollow"
    - name: "googlebot"
      content: "noindex, nofollow"
    - name: "description"
      content: "StatUwUs is a simple status page for services and website used/created by a so-called e-girl who is not."
    - name: "author"
      content: "So-called e-girl who is not."
  customBodyHtml: "

  <div class='icon-bar'>
    <a href='https://www.instagram.com/antighostping' target='_blank' title='Instagram' class='instagram'><i class='fa-brands fa-instagram'></i></a>
    <a href='https://github.com/byFrench' target='_blank' title='GitHub' class='github'><i class='fa-brands fa-github'></i></a>
    <a href='https://twitter.com/antighostping' target='_blank' title='X / Twitter' class='x-twitter'><i class='fa-brands fa-x-twitter'></i></a>
  </div>

  "


# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
